### ISSUE TITLE
TypeError: Terminal is not a constructor

### ISSUE THREAD

**Issue by InvalidJoker** [BattlefieldDuck/xterm-svelte#107]
**Describe the bug**  
The error `Uncaught (in promise) TypeError: Terminal is not a constructor` occurs when the `on mount` event is triggered. The error happens while trying to instantiate the `Terminal` class from the library.

**To Reproduce**  
1. Import the `Xterm` and `XtermAddon` components from `@battlefieldduck/xterm-svelte`.
2. Attempt to mount the `Xterm` component on a page.
3. Look at the error in the browser console.

**Expected behavior**  
The `Terminal` instance should be created successfully, and the terminal should initialize without any errors.

**Screenshots**  

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser: Chrome

**Additional context**  
/

**Comment by InvalidJoker** [comment]
![image](https://github.com/user-attachments/assets/0fd0df17-fdb1-443a-9565-1aeb6e740867)

**Comment by BattlefieldDuck** [comment]
What is your svelte version

**Comment by InvalidJoker** [comment]
> What is your svelte version

tried with 5.0.0 and 5.1.13

**Comment by BattlefieldDuck** [comment]
Is it possible to show your code that the error occurs? thanks.

**Comment by InvalidJoker** [comment]
sure:

component:
```svelte
<script lang="ts">
	import { Xterm, XtermAddon } from '@battlefieldduck/xterm-svelte';
	import type {
		ITerminalOptions,
		ITerminalInitOnlyOptions,
		Terminal
	} from '@battlefieldduck/xterm-svelte';

	let options: ITerminalOptions & ITerminalInitOnlyOptions = {
		fontFamily: 'Consolas'
	};

	async function onLoad(terminal: Terminal) {
		console.log('Child component has loaded');

		// FitAddon Usage
		const fitAddon = new (await XtermAddon.FitAddon()).FitAddon();
		terminal.loadAddon(fitAddon);
		fitAddon.fit();

		terminal.write('Hello World');
	}

	function onData(data: string) {
		console.log('onData()', data);
	}

	function onKey(data: { key: string; domEvent: KeyboardEvent }) {
		console.log('onKey()', data);
	}
</script>

<div class="terminal">
	<Xterm {options} {onLoad} {onData} {onKey} />
</div>
```

it's just inside a melt tab

**Comment by BattlefieldDuck** [comment]
how do you load this child component?

**Comment by InvalidJoker** [comment]
```svelte
		<div
			class="relative items-center rounded-xl border border-black/20 bg-slate-200 p-3 text-zinc-950 dark:border-white/20 dark:bg-zinc-800/40 dark:text-zinc-100"
		>
			<div use:melt={$content('overview')}>
				<h1>Dashboard</h1>
				<p>This is the dashboard page</p>
				<Terminal2 />
			</div>
		</div>
		<div class="py-24"></div>
```

**Comment by BattlefieldDuck** [comment]
What `@battlefieldduck/xterm-svelte` version are you using?

**Comment by InvalidJoker** [comment]
> What `@battlefieldduck/xterm-svelte` version are you using?

newest 2.0.0

**Comment by BattlefieldDuck** [comment]
Try uninstall `npm uninstall @battlefieldduck/xterm-svelte` and install `npm install @battlefieldduck/xterm-svelte` again.

**Comment by InvalidJoker** [comment]
> Try uninstall `npm uninstall @battlefieldduck/xterm-svelte` and install `npm install @battlefieldduck/xterm-svelte` again.

done, doesn't help

**Comment by BattlefieldDuck** [comment]
What if the `<Terminal2 />` component is outside the `<div use:melt={$content('overview')}>`?

**Comment by InvalidJoker** [comment]
tried with a blank page, doesnt work

**Comment by BattlefieldDuck** [comment]
Do you have a GitHub project repository that I can take a look at?

**Comment by InvalidJoker** [comment]
> Do you have a GitHub project repository that I can take a look at?

Unfortunately it's not public

**Comment by BattlefieldDuck** [comment]
I just created a new github repo `xterm-svelte-example` with sveltekit (svelte5) and xterm-svelte installed.

https://github.com/BattlefieldDuck/xterm-svelte-example

You can test it with `npm i` and `npm run dev`. You should be able to see the terminal on while `npm run dev`.

You may try comparing the settings of the projects. I hope it helps.

**Comment by InvalidJoker** [comment]
Hey, thank you the project you provided works. I will now compare it with my code
